<a href="https://colab.research.google.com/github/whuang1101/Machine-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [3]:
#scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [14]:
MATRIX = torch.tensor([[7,8],
                      [9,10],
                       [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [18]:
MATRIX.shape

torch.Size([3, 2])

In [20]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [29]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

In [32]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8417, 0.8054, 0.1769, 0.7761],
        [0.6666, 0.9209, 0.3034, 0.6874],
        [0.7874, 0.1740, 0.1023, 0.0730]])

In [37]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [4]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [14]:
one_to_ten = torch.arange(0,10)
tenzeros = torch.zeros_like(input=one_to_ten)
tenzeros = tenzeros.type(torch.float32)
float_16_tensor = tenzeros.type(torch.float16)
float_16_tensor * tenzeros
float_16_tensor.dtype , tenzeros.dtype

(torch.float16, torch.float32)

### Manipulating Tensors (tensor operations)


Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [21]:
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10
tensor - 10
tensor

tensor = torch.tensor([1,2,3])

print(torch.matmul(tensor,tensor))

tensor(14)


"

In [24]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one ou our tensors using transpose,


In [31]:
%%time
tensor_B.T, tensor_B.T.shape
torch.mm(tensor_A,tensor_B.T)


CPU times: user 114 µs, sys: 7 µs, total: 121 µs
Wall time: 125 µs


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [33]:
## Finding the min, max, mean, sum, etc(tensor aggregation)

In [39]:
# Create a tensor
x = torch.arange(0,100,10)
torch.min(x), x.min()
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [42]:
torch.mean(x.type(torch.float32))

tensor(45.)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tesnor of certain shape but keep the same memory as the orignal tensor
* Stacking- combine multiple tensors on top of each other(vstack or side by side (hstack))
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tesnor
* Permute - Return a view of the input with dimensions permuted in a certian way


In [45]:
import torch
x = torch.arange(1,10)
x, x.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [48]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Change the view